/**
 * @author WMXPY
 * @namespace Capability
 * @description Origin
 */

import { IMBRICATE_CAPABILITY_EFFECT, IMBRICATE_ORIGIN_CAPABILITY_KEY, ImbricateOriginCapability } from "@imbricate/core";

export const createImbricateOriginCapability = (): ImbricateOriginCapability => {

    return {
        [IMBRICATE_ORIGIN_CAPABILITY_KEY.CREATE_COLLECTION]: {
            effect: IMBRICATE_CAPABILITY_EFFECT.ALLOW,
        },
        [IMBRICATE_ORIGIN_CAPABILITY_KEY.RENAME_COLLECTION]: {
            effect: IMBRICATE_CAPABILITY_EFFECT.ALLOW,
        },
        [IMBRICATE_ORIGIN_CAPABILITY_KEY.DELETE_COLLECTION]: {
            effect: IMBRICATE_CAPABILITY_EFFECT.ALLOW,
        },
        [IMBRICATE_ORIGIN_CAPABILITY_KEY.GET_COLLECTION]: {
            effect: IMBRICATE_CAPABILITY_EFFECT.ALLOW,
        },
        [IMBRICATE_ORIGIN_CAPABILITY_KEY.LIST_COLLECTIONS]: {
            effect: IMBRICATE_CAPABILITY_EFFECT.ALLOW,
        },
        [IMBRICATE_ORIGIN_CAPABILITY_KEY.CREATE_SCRIPT]: {
            effect: IMBRICATE_CAPABILITY_EFFECT.ALLOW,
        },
        [IMBRICATE_ORIGIN_CAPABILITY_KEY.PUT_SCRIPT]: {
            effect: IMBRICATE_CAPABILITY_EFFECT.ALLOW,
        },
        [IMBRICATE_ORIGIN_CAPABILITY_KEY.RENAME_SCRIPT]: {
            effect: IMBRICATE_CAPABILITY_EFFECT.ALLOW,
        },
        [IMBRICATE_ORIGIN_CAPABILITY_KEY.DELETE_SCRIPT]: {
            effect: IMBRICATE_CAPABILITY_EFFECT.ALLOW,
        },
        [IMBRICATE_ORIGIN_CAPABILITY_KEY.GET_SCRIPT]: {
            effect: IMBRICATE_CAPABILITY_EFFECT.ALLOW,
        },
        [IMBRICATE_ORIGIN_CAPABILITY_KEY.LIST_SCRIPTS]: {
            effect: IMBRICATE_CAPABILITY_EFFECT.ALLOW,
        },
    };
};
